version: "3.8"
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
